'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
type Content=any;
const setPath=(o:any,path:string,value:string)=>{const p=path.split('.');let x=o;for(let i=0;i<p.length-1;i++)x=x[p[i]];x[p.at(-1)!]=value};
export default function Admin(){
 const [password,setPassword]=useState(''),[content,setContent]=useState<Content|null>(null),[message,setMessage]=useState('');const previewRef=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{if(content)previewRef.current?.contentWindow?.postMessage({type:'crr-preview',content},window.location.origin)},[content]);
 const change=(path:string,value:string)=>setContent((old:Content)=>{const copy=structuredClone(old);setPath(copy,path,value);return copy});
 async function login(e:FormEvent){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok){setMessage((await r.json()).error);return}setContent(await fetch('/api/admin/content').then(x=>x.json()))}
 async function save(){setMessage('Сохраняю…');const r=await fetch('/api/admin/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(content)});setMessage(r.ok?'Сохранено. Сайт обновится автоматически примерно за минуту.':(await r.json()).error)}
 async function upload(index:number,file:File,target?:string){const base64=await new Promise<string>((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=bad;r.readAsDataURL(file)});setMessage('Загружаю…');const r=await fetch('/api/admin/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,base64})});const data=await r.json();if(!data.url){setMessage(data.error);return}if(index===-1)change('header.logoImage',data.url);else if(target)change(target+'.image',data.url);else change('galleryImages.'+index,data.url);setMessage('Готово. Нажми «Сохранить изменения».')}
 if(!content)return <main className="admin-shell"><form className="login-card" onSubmit={login}><p className="eyebrow gold">ЦЕНТР РАЗМНОЖЕНИЯ РАСТЕНИЙ</p><h1>Вход в редактор</h1><p>Доступ только для владельца сайта.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Пароль" required/><button className="gold-btn">Войти <span>↗</span></button>{message&&<small>{message}</small>}</form></main>;
 return <main className="admin-shell"><header className="admin-head"><a href="/">← Открыть сайт</a><div><b>Редактор сайта</b><button onClick={save} className="gold-btn">Сохранить изменения</button></div></header><div className="editor-layout"><div className="admin-wrap"><p className="admin-message">{message||'Меняй всё нужное и нажми «Сохранить изменения». Сайт обновится автоматически.'}</p>
 <section><h2>Шапка, логотип и шрифты</h2><label>Название в шапке<input value={content.header.title} onChange={e=>change('header.title',e.target.value)}/></label><label>Подпись под названием<input value={content.header.subtitle} onChange={e=>change('header.subtitle',e.target.value)}/></label><label>Логотип<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(-1,e.target.files[0])}/></label><label>Шрифт заголовков<select value={content.appearance.headingFont} onChange={e=>change('appearance.headingFont',e.target.value)}><option>Playfair Display</option><option>Georgia</option><option>Manrope</option><option>Arial</option></select></label><label>Основной шрифт<select value={content.appearance.bodyFont} onChange={e=>change('appearance.bodyFont',e.target.value)}><option>Manrope</option><option>Arial</option><option>Georgia</option></select></label></section>
 <section><h2>Первый экран</h2><label>Строка над заголовком<input value={content.hero.eyebrow} onChange={e=>change('hero.eyebrow',e.target.value)}/></label><label>Заголовок<input value={content.hero.title} onChange={e=>change('hero.title',e.target.value)}/></label><label>Золотая строка<input value={content.hero.accent} onChange={e=>change('hero.accent',e.target.value)}/></label><label>Описание<textarea value={content.hero.intro} onChange={e=>change('hero.intro',e.target.value)}/></label><label>Фоновое фото первого экрана<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(-2,e.target.files[0],'hero')}/></label></section>
 <section><h2>Контакты</h2><label>Главный телефон<input value={content.phone} onChange={e=>change('phone',e.target.value)}/></label><label>Номер для звонка — только цифры<input value={content.phoneLink} onChange={e=>change('phoneLink',e.target.value)}/></label><label>Почта<input value={content.email} onChange={e=>change('email',e.target.value)}/></label><label>Адрес<input value={content.address} onChange={e=>change('address',e.target.value)}/></label>{content.contacts.map((x:any,i:number)=><div className="contact-edit" key={i}><b>Контакт {i+1}</b><input value={x.name} onChange={e=>change('contacts.'+i+'.name',e.target.value)}/><input value={x.label} onChange={e=>change('contacts.'+i+'.label',e.target.value)}/><input value={x.phone} onChange={e=>change('contacts.'+i+'.phone',e.target.value)} placeholder="Номер для звонка"/></div>)}</section>
 <section><h2>Теплицы и маточник</h2>{['greenhouse','mother'].map(key=><div className="contact-edit" key={key}><b>{key==='greenhouse'?'Тепличный комплекс':'Маточник'}</b><input value={content[key].title} onChange={e=>change(key+'.title',e.target.value)}/><input value={content[key].accent} onChange={e=>change(key+'.accent',e.target.value)}/><textarea value={content[key].text} onChange={e=>change(key+'.text',e.target.value)}/><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(-2,e.target.files[0],key)}/></div>)}</section>
 <section><h2>Специализация и прайс</h2><label>Заголовок<input value={content.specialty.title} onChange={e=>change('specialty.title',e.target.value)}/></label><label>Текст<textarea value={content.specialty.paragraph1} onChange={e=>change('specialty.paragraph1',e.target.value)}/></label><label>Текст 2<textarea value={content.specialty.paragraph2} onChange={e=>change('specialty.paragraph2',e.target.value)}/></label><label>Ссылка на прайс<input value={content.priceUrl} onChange={e=>change('priceUrl',e.target.value)} placeholder="https://…"/></label></section>
 <section><h2>Ассортимент</h2>{content.assortment.map((x:string,i:number)=><label key={i}>Позиция {i+1}<input value={x} onChange={e=>change('assortment.'+i,e.target.value)}/></label>)}<button type="button" className="outline-btn" onClick={()=>setContent((o:Content)=>({...o,assortment:[...o.assortment,'Новая культура']}))}>Добавить культуру</button></section>
 <section><h2>Фотографии</h2><div className="upload-grid">{content.galleryImages.map((url:string,i:number)=><label className="upload" key={i} style={{backgroundImage:'url('+url+')'}}><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(i,e.target.files[0])}/><span>Заменить фото</span></label>)}</div><button type="button" className="outline-btn" onClick={()=>setContent((o:Content)=>({...o,galleryImages:[...o.galleryImages,'']}))}>Добавить фото</button></section>
 <section><h2>Видео</h2><p>Вставь ссылку на YouTube — видео появится на сайте.</p>{content.videos.map((v:any,i:number)=><div className="contact-edit" key={i}><input value={v.title} onChange={e=>change('videos.'+i+'.title',e.target.value)} placeholder="Название видео"/><input value={v.url} onChange={e=>change('videos.'+i+'.url',e.target.value)} placeholder="https://www.youtube.com/watch?v=…"/></div>)}<button type="button" className="outline-btn" onClick={()=>setContent((o:Content)=>({...o,videos:[...o.videos,{title:'Новое видео',url:''}]}))}>Добавить видео</button></section>
 <section><h2>Полезные ссылки</h2>{content.resources.map((x:any,i:number)=><div className="contact-edit" key={i}><input value={x.title} onChange={e=>change('resources.'+i+'.title',e.target.value)}/><input value={x.url} onChange={e=>change('resources.'+i+'.url',e.target.value)} placeholder="Ссылка"/></div>)}</section></div><aside className="preview-panel"><div className="preview-label"><span>Предпросмотр</span><small>Изменения видны сразу</small></div><div className="preview-frame"><iframe ref={previewRef} src="/" title="Предпросмотр сайта" onLoad={()=>previewRef.current?.contentWindow?.postMessage({type:'crr-preview',content},window.location.origin)}/></div></aside></div></main>}
